  (int)(ptrdiff_t)&((struct stringpool2_t *)0)->stringpool_extra_0,
  (int)(ptrdiff_t)&((struct stringpool2_t *)0)->stringpool_extra_2,
  (int)(ptrdiff_t)&((struct stringpool2_t *)0)->stringpool_extra_4,
  (int)(ptrdiff_t)&((struct stringpool2_t *)0)->stringpool_extra_6,
  (int)(ptrdiff_t)&((struct stringpool2_t *)0)->stringpool_extra_7,
  (int)(ptrdiff_t)&((struct stringpool2_t *)0)->stringpool_extra_9,
  (int)(ptrdiff_t)&((struct stringpool2_t *)0)->stringpool_extra_11,
